/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:9d714628-908c-4b3a-9dc8-95eac7bd3aa0",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_HdgSmycrq",
    "aws_user_pools_web_client_id": "4rjoam269hh8s79gu07seg6o03",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ChargePoint-dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "ChargePoint",
            "endpoint": "https://asodea7xj7.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
